### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by FichteFoll** [SublimeText/ScopeNamingGuidelines#1]
The contents of this repository should be licensed so they can be copied, cited, shared or otherwise modified freely. The contents are targeted to be a resource for the public, so the license should be as permissive as possible to increase its reach and remove unnecessary worries.

Examples in the wild:

- Rust dual-licenses its RFCs under the Apache-2.0 and MIT licenses. ([ref](https://github.com/rust-lang/rfcs/blob/master/text/2044-license-rfcs.md)) 
- Python's PEP currently default to "public domain and CC0-1.0-Universal". ([ref](https://github.com/brettcannon/peps/commit/1618124399b3ae4aba998d400bd9865493a97970)) 
- The IETF uses [something custom](https://trustee.ietf.org/trust-legal-provisions.html).

Questions for us:

1. What license model should we default to?
2. Should we require all documents to be put under that license or should we add per-document copyright notices/licenses in the last section?

---

Personally, I'm very much in favor of Python's "public domain and CC0" model (or just CC-0, which is basically the same in legal, because it is the most permissive model I know and CC is generally more applicative for non-code works. The next level would be CC-BY, which I doubt is something we would care for since this project is about the ecosystem as a whole.
For 2), I suggest requiring this license for the entire repository until we find a use case or reason to do otherwise. Going from very permissive to not as permissive is much easier than vice versa and we don't have the same boilerplate text on every document.

Furthermore, I hope that if we play it right, we don't need to bother with CLAs or similar, but my experience with that is limited and IANAL.

**Comment by tajmone** [comment]
Defintely the repository needs a license.

I'm all-in for CC0, but if public domain is not an option let's at least use a documentation-oriented license — e.g. Creative Commons.

The good thing about CC licenses are that they are designed with contents in mind, and they are clear about derivative works (e.g. even with CC-BY-SA-ND, coverting from markdown to HTML wouldn't qualify as derivative work).

Using code-licenses can lead to confusion IMO, especially since these markdown docs will contain code inside their examples (possibly, also third pary code), which complicates all matters, whereas with CC licenses it's clear the separation between original contents and third party code in examples being ruled by its own license.

**Comment by FichteFoll** [comment]
Added via b0a956b2c71956a4469cd731350e16863e44d5d9.
