### ISSUE TITLE
Strange hard wrapping in base scope document

### ISSUE THREAD

**Issue by deathaxe** [SublimeText/ScopeNamingGuidelines#8]
Why do you use hard wrapping in markdown documents at all?

If hardwrapping is used, shouldn't it wrap at something common like 80 chars rather than 40?

**Comment by FichteFoll** [comment]
See https://github.com/SublimeText/ScopeNamingGuidelines/blob/9f8837af966e47cc39f2da25c177d634cf221341/CONTRIBUTING.md#style. I use this style in all my text-based projects, notably for documentation, and it makes version control much simpler when sentences are broken at semantic break points rather than arbitrary column widths.

**Comment by deathaxe** [comment]
I can remember heavy critics when I used to hard wrap markdown files in GitGutter's documentation several years ago about that not being a good style.

**Comment by FichteFoll** [comment]
Opinions may differ on this, although I haven't come to see any strong arguments for not using semantic linefeeds. I can only think of text being slightly easier to read if the lines are longer and justified, but that is arguably subjective since people probably consider sentences to have pauses at slightly different places and some may prefer shorter lines in general.

Since I initiated this repository, I get to choose the style. 🙂 I'm open for debates on this, but so far I haven't had much of an opposition. It might also just be something that you need to try out first before you can judge properly.

**Comment by deathaxe** [comment]
It's indeed the first time I ever have seen such a style in markdown files. The arguments for it sound more logical to use than hard wrapped lines at a certain column, with regards to reworking/updateing texts. It looks a bit like poetry this way.
